services:
  seerr:
    image: seerr/seerr:v3.0.1
    environment:
      - TZ=America/Chicago
    volumes:
      - /home/jaw/data/seerr:/app/config
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    labels:
      caddy: seerr.jaw.dev
      caddy.import: auth
      caddy.reverse_proxy: "{{upstreams 5055}}"

networks:
  proxy:
    external: true
