services:
  stirling-pdf:
    image: frooodle/s-pdf:2.4.5@sha256:005f4174c00006c0771b020c77fd9fdad334e112d629a8583671e8fe5eeb17f5
    environment:
      - TZ=America/Chicago
      - DOCKER_ENABLE_SECURITY=true
    volumes:
      - /home/jaw/data/stirling-pdf:/usr/share/tessdata
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.jaw.dev`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.middlewares=authelia@file"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
