services:
  stirling-pdf:
    image: frooodle/s-pdf:2.4.6@sha256:073023f9829b96a5e64ec3cdbf2f441e65feb8b89bfbebeae217b96564b546e9
    environment:
      - TZ=America/Chicago
      - DOCKER_ENABLE_SECURITY=true
    volumes:
      - /home/jaw/data/stirling-pdf:/usr/share/tessdata
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1.5G
    labels:
      caddy: pdf.jaw.dev
      caddy.import: auth
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  proxy:
    external: true
