services:
  hello-world:
    image: ghcr.io/wajeht/docker-cd-hello-world:d220756
    env_file:
      - .enc.env
      - .enc-temp.env
    networks:
      - traefik
      - internal
    depends_on:
      hello-world-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello-world-pr-1.rule=Host(`pr-1-hello-world.jaw.dev`)
      - traefik.http.routers.hello-world-pr-1.entrypoints=websecure
      - traefik.http.routers.hello-world-pr-1.tls=true
      - traefik.http.services.hello-world-pr-1.loadbalancer.server.port=3000
    healthcheck:
      test:
        - CMD
        - wget
        - "--spider"
        - "-q"
        - http://localhost:3000/healthz
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  hello-world-db:
    image: postgres:17-alpine
    env_file:
      - .enc.env
      - .enc-temp.env
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_DB=hello
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U hello -d hello
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
networks:
  traefik:
    external: true
  internal: null
volumes:
  db: null
