services:
  screenshot:
    image: ghcr.io/wajeht/screenshot:88a521b
    environment:
      TZ: America/Chicago
      APP_ENV: production
      APP_PORT: 80
    env_file:
      - .enc.env
    volumes:
      - /home/jaw/data/screenshot:/app/data
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screenshot.rule=Host(`screenshot.jaw.dev`)"
      - "traefik.http.routers.screenshot.entrypoints=websecure"
      - "traefik.http.services.screenshot.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
