services:
  screenshot:
    image: ghcr.io/wajeht/screenshot:5eb685d
    environment:
      TZ: America/Chicago
      APP_ENV: production
      APP_PORT: 80
    env_file:
      - .env
    volumes:
      - /home/jaw/data/screenshot:/app/data
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    labels:
      caddy: screenshot.jaw.dev
      caddy.import: public
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  proxy:
    external: true
