services:
  linx:
    image: andreimarcu/linx-server:version-2.3.8@sha256:d969c23e6c324a978f47b2a321384be5781032f660045a46f7a06746f0a4cb06
    command: -config /config/linx.conf
    volumes:
      - ./config:/config
      - /home/jaw/data/linx/files:/files
      - /home/jaw/data/linx/meta:/meta
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linx.rule=Host(`linx.jaw.dev`)"
      - "traefik.http.routers.linx.entrypoints=websecure"
      - "traefik.http.routers.linx.middlewares=auth-admin@file"
      - "traefik.http.services.linx.loadbalancer.server.port=8080"
networks:
  traefik:
    external: true
