services:
  bang:
    image: ghcr.io/wajeht/bang:d8364c2
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bang-pr-174.rule=Host(`pr-174-bang.jaw.dev`)"
      - "traefik.http.routers.bang-pr-174.entrypoints=websecure"
      - "traefik.http.services.bang-pr-174.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik:
    external: true
