- Media:
    - Plex:
        icon: plex
        href: https://plex.jaw.dev
        description: Movies & TV
        siteMonitor: http://plex:32400

    - Radarr:
        icon: radarr
        href: https://radarr.jaw.dev
        description: Movies
        siteMonitor: http://radarr:7878
        widget:
          type: radarr
          url: http://radarr:7878
          key: "{{HOMEPAGE_VAR_RADARR_KEY}}"

    - Sonarr:
        icon: sonarr
        href: https://sonarr.jaw.dev
        description: TV Shows
        siteMonitor: http://sonarr:8989
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: "{{HOMEPAGE_VAR_SONARR_KEY}}"

    - Tautulli:
        icon: tautulli
        href: https://tautulli.jaw.dev
        description: Plex Stats
        siteMonitor: http://tautulli:8181
        widget:
          type: tautulli
          url: http://tautulli:8181
          key: "{{HOMEPAGE_VAR_TAUTULLI_KEY}}"

    - Bazarr:
        icon: bazarr
        href: https://bazarr.jaw.dev
        description: Subtitles
        siteMonitor: http://bazarr:6767

    - Seerr:
        icon: overseerr
        href: https://seerr.jaw.dev
        description: Media Requests
        siteMonitor: http://seerr:5055

    - Audiobookshelf:
        icon: audiobookshelf
        href: https://audiobooks.jaw.dev
        description: Audiobooks
        siteMonitor: http://audiobookshelf:80

    - Miniflux:
        icon: miniflux
        href: https://rss.jaw.dev
        description: RSS Reader
        siteMonitor: http://miniflux:8080
        widget:
          type: miniflux
          url: http://miniflux:8080
          key: "{{HOMEPAGE_VAR_MINIFLUX_KEY}}"

- Downloaders:
    - SABnzbd:
        icon: sabnzbd
        href: https://sabnzbd.jaw.dev
        description: Usenet
        siteMonitor: http://sabnzbd:8080
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: "{{HOMEPAGE_VAR_SABNZBD_KEY}}"

    - qBittorrent:
        icon: qbittorrent
        href: https://qbit.jaw.dev
        description: Torrents
        siteMonitor: http://gluetun:8085
        widget:
          type: qbittorrent
          url: http://gluetun:8085
          username: "{{HOMEPAGE_VAR_QBIT_USER}}"
          password: "{{HOMEPAGE_VAR_QBIT_PASS}}"

    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.jaw.dev
        description: Indexers
        siteMonitor: http://prowlarr:9696

    - Autobrr:
        icon: autobrr
        href: https://autobrr.jaw.dev
        description: Download Automation
        siteMonitor: http://autobrr:7474

    - Bitmagnet:
        icon: bitmagnet
        href: https://bitmagnet.jaw.dev
        description: DHT Indexer
        siteMonitor: http://bitmagnet:3333

    - Huntarr:
        icon: huntarr
        href: https://huntarr.jaw.dev
        description: Missing Media Hunter
        siteMonitor: http://huntarr:9705

    - Cleanuparr:
        icon: cleanuparr
        href: https://cleanuparr.jaw.dev
        description: Download Cleanup
        siteMonitor: http://cleanuparr:11011

- Infrastructure:
    - Traefik:
        icon: traefik
        href: https://traefik.jaw.dev
        description: Reverse Proxy
        siteMonitor: http://traefik:8080
        widget:
          type: traefik
          url: http://traefik:8080

    - Uptime Kuma:
        icon: uptime-kuma
        href: https://status.jaw.dev
        description: Status Monitor
        siteMonitor: http://uptime-kuma:3001
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: status
          key: "{{HOMEPAGE_VAR_UPTIME_KUMA_KEY}}"

    - Docker-CD:
        icon: docker
        href: https://cd.jaw.dev
        description: GitOps Deployer
        siteMonitor: http://docker-cd:80

    - Google Auth:
        icon: google
        href: https://auth.jaw.dev
        description: OAuth Proxy
        siteMonitor: http://google-auth:4181

    - Changedetection:
        icon: changedetection-io
        href: https://changes.jaw.dev
        description: Web Monitor
        siteMonitor: http://changedetection:5000

    - Ntfy:
        icon: ntfy
        href: https://ntfy.jaw.dev
        description: Notifications
        siteMonitor: http://ntfy:80

    - Portainer:
        icon: portainer
        href: https://portainer.jaw.dev
        description: Docker Management
        siteMonitor: http://portainer:9000

    - Renovate:
        icon: renovate
        href: https://renovate.jaw.dev
        description: Dependency Updates
        siteMonitor: http://renovate:8080

    - GlitchTip:
        icon: glitchtip
        href: https://glitchtip.jaw.dev
        description: Error Tracking
        siteMonitor: http://glitchtip:8000

    - Dozzle:
        icon: dozzle
        href: https://logs.jaw.dev
        description: Docker Logs
        siteMonitor: http://dozzle:8080

    - Plausible:
        icon: plausible
        href: https://plausible.jaw.dev
        description: Web Analytics
        siteMonitor: http://plausible:8000

- Apps:
    - UFC:
        icon: mdi-mixed-martial-arts
        href: https://ufc.jaw.dev
        description: MMA Calendar
        siteMonitor: http://ufc:80

    - Calendar:
        icon: mdi-calendar
        href: https://calendar.jaw.dev
        description: Personal Calendar
        siteMonitor: http://calendar:80

    - Favicon:
        icon: mdi-image-search
        href: https://favicon.jaw.dev
        description: Favicon Grabber
        siteMonitor: http://favicon:80

    - Screenshot:
        icon: mdi-monitor-screenshot
        href: https://screenshot.jaw.dev
        description: Screenshot API
        siteMonitor: http://screenshot:80

    - Bang:
        icon: duckduckgo
        href: https://bang.jaw.dev
        description: Search Redirector
        siteMonitor: http://bang:80

    - Gains:
        icon: mdi-weight-lifter
        href: https://gains.jaw.dev
        description: Workout Tracker
        siteMonitor: http://gains:80

    - Notify:
        icon: mdi-bell
        href: https://notify.jaw.dev
        description: Notifications
        siteMonitor: http://notify:80

    - IP:
        icon: mdi-ip-network
        href: https://ip.jaw.dev
        description: IP Lookup
        siteMonitor: http://ip:80

    - Close Powerlifting:
        icon: mdi-weight-lifter
        href: https://close-powerlifting.jaw.dev
        description: Powerlifting Stats
        siteMonitor: http://close-powerlifting:80

    - MM2US:
        icon: mdi-swap-horizontal
        href: https://mm2us.com
        description: Unit Converter
        siteMonitor: https://mm2us.com

- Tools:
    - Vaultwarden:
        icon: vaultwarden
        href: https://vault.jaw.dev
        description: Passwords
        siteMonitor: http://vaultwarden:80

    - Stirling PDF:
        icon: stirling-pdf
        href: https://pdf.jaw.dev
        description: PDF Tools
        siteMonitor: http://stirling-pdf:8080

    - IT-Tools:
        icon: it-tools
        href: https://tools.jaw.dev
        description: Dev Utilities
        siteMonitor: http://it-tools:80

    - Paperless:
        icon: paperless-ngx
        href: https://paperless.jaw.dev
        description: Documents
        siteMonitor: http://paperless:8000

    - Zipline:
        icon: zipline
        href: https://img.jaw.dev
        description: Image Sharing
        siteMonitor: http://0.0.0.0:3000

    - SearXNG:
        icon: searxng
        href: https://search.jaw.dev
        description: Search Engine
        siteMonitor: http://searxng:8080

    - Linx:
        icon: filerun
        href: https://linx.jaw.dev
        description: File Sharing
        siteMonitor: http://linx:8080

- Dev:
    - Code Server:
        icon: vscode
        href: https://code.jaw.dev
        description: Web IDE
        siteMonitor: http://code-server:8080

    - WWW:
        icon: mdi-web
        href: https://jaw.dev
        description: Personal Site
        siteMonitor: https://jaw.dev

    - Commit:
        icon: git
        href: https://commit.jaw.dev
        description: AI Commits
        siteMonitor: http://commit:80

    - Gitea:
        icon: gitea
        href: https://gitea.jaw.dev
        description: Git Mirror
        siteMonitor: http://gitea:3000

    - GitHub:
        icon: github
        href: https://github.com/wajeht
        description: Profile

    - Home Ops:
        icon: github
        href: https://github.com/wajeht/home-ops
        description: This Repo

    - Git Redirect:
        icon: git
        href: https://git.jaw.dev
        description: Git URL Shortener
        siteMonitor: http://git:80
