title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: false
showStats: true
cardBlur: sm
maxGroupColumns: 3
layout:
  Infrastructure:
    style: column
  Media:
    style: column
  Tools:
    style: column
  Apps:
    style: column
  Developer:
    style: column
