title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: false
showStats: true
cardBlur: sm
layout:
  Infra:
    style: column
  Monitoring:
    style: column
  Media:
    style: column
  Arr Stack:
    style: column
  Tools:
    style: column
  Dev:
    style: column
