title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: boxedWidgets
hideVersion: true
showStats: true
cardBlur: sm
fiveColumns: true
statusStyle: dot
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
layout:
  Media:
    style: column
    tab: Services
  Infrastructure:
    style: column
    tab: Services
  Apps:
    style: column
    tab: Apps
  Tools:
    style: column
    tab: Apps
  Dev:
    style: column
    tab: Dev
