title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: false
showStats: true
layout:
  Infrastructure:
    style: row
    columns: 4
  Media Streaming:
    style: row
    columns: 3
  Media Management:
    style: row
    columns: 3
  Productivity:
    style: row
    columns: 4
  Development:
    style: row
    columns: 4
  Services:
    style: row
    columns: 2
  Developer:
    style: column
