title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: false
showStats: true
layout:
  Infrastructure:
    style: row
    columns: 3
  Media:
    style: row
    columns: 4
  Monitoring:
    style: column
  Tools:
    style: row
    columns: 4
  Apps:
    style: column
  Developer:
    style: column
