title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: false
showStats: true
cardBlur: sm
layout:
  Infrastructure:
    style: column
    header: true
  Media:
    style: column
    header: true
  Tools:
    style: column
    header: true
  Developer:
    style: column
    header: true
