title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: true
showStats: false
cardBlur: sm
layout:
  Infrastructure:
    style: column
  Media:
    style: column
  Downloads:
    style: column
  Tools:
    style: column
