title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: clean
hideVersion: true
showStats: false
cardBlur: sm
fiveColumns: true
layout:
  Media:
    style: column
    column: 1
  Infrastructure:
    style: column
    column: 2
  Apps:
    style: column
    column: 3
  Tools:
    style: column
    column: 4
  Dev:
    style: column
    column: 5
