- openmeteo:
    label: Dallas
    latitude: 32.7767
    longitude: -96.7970
    units: imperial
    cache: 5

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    units: imperial
    uptime: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
