- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: imperial
    uptime: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
