- openmeteo:
    label: Amarillo
    latitude: 35.2220
    longitude: -101.8313
    units: imperial
    cache: 5

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    units: imperial
    uptime: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
