services:
  google-auth:
    container_name: google-auth
    image: thomseddon/traefik-forward-auth:2@sha256:69a2c985d2c518b6f0e77161a98628a148a5d964e4e84fc52cc62e19bb4da634
    command:
      - --rule.user.action=auth
      - --rule.user.rule=Host(`seerr.jaw.dev`) || Host(`plex.jaw.dev`)
      - --rule.bypass.action=allow
      - --rule.bypass.rule=HeadersRegexp(`X-Bypass-Key`, `^${X_BYPASS_KEY}$$`)
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
      - DEFAULT_PROVIDER=google
      - AUTH_HOST=auth.jaw.dev
      - COOKIE_DOMAIN=jaw.dev
      - INSECURE_COOKIE=true
      - LOG_LEVEL=info
      - WHITELIST=${WHITELIST_ADMINS}
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.google-auth.rule=Host(`auth.jaw.dev`)"
      - "traefik.http.routers.google-auth.entrypoints=websecure"
      - "traefik.http.routers.google-auth.middlewares=google-auth@file"
      - "traefik.http.services.google-auth.loadbalancer.server.port=4181"

networks:
  traefik:
    external: true
