services:
  google-auth-user:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - TZ=America/Chicago
      - DEFAULT_PROVIDER=google
      - AUTH_HOST=auth.jaw.dev
      - COOKIE_DOMAIN=jaw.dev
      - COOKIE_NAME=_forward_auth_user
      - SECRET=${SECRET}
      - PROVIDERS_GOOGLE_CLIENT_ID=${PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${PROVIDERS_GOOGLE_CLIENT_SECRET}
      - WHITELIST=${WHITELIST}
      - INSECURE_COOKIE=true
      - LOG_LEVEL=info
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.google-auth.rule=Host(`auth.jaw.dev`)"
      - "traefik.http.routers.google-auth.entrypoints=websecure"
      - "traefik.http.services.google-auth.loadbalancer.server.port=4181"

  google-auth-admin:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - TZ=America/Chicago
      - DEFAULT_PROVIDER=google
      - AUTH_HOST=auth.jaw.dev
      - COOKIE_DOMAIN=jaw.dev
      - COOKIE_NAME=_forward_auth_admin
      - SECRET=${SECRET}
      - PROVIDERS_GOOGLE_CLIENT_ID=${PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${PROVIDERS_GOOGLE_CLIENT_SECRET}
      - WHITELIST=${WHITELIST_ADMINS:-no-one@example.invalid}
      - INSECURE_COOKIE=true
      - LOG_LEVEL=info
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M

networks:
  traefik:
    external: true
