services:
  google-auth-user:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - TZ=America/Chicago
      - DEFAULT_PROVIDER=google
      - AUTH_HOST=auth.jaw.dev
      - URL_PATH=/_oauth_user
      - COOKIE_DOMAIN=jaw.dev
      - COOKIE_NAME=_forward_auth_user
      - CSRF_COOKIE_NAME=_forward_auth_user_csrf
      - SECRET=${SECRET}
      - PROVIDERS_GOOGLE_CLIENT_ID=${PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${PROVIDERS_GOOGLE_CLIENT_SECRET}
      - WHITELIST=${WHITELIST}
      - INSECURE_COOKIE=false
      - LOG_LEVEL=info
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.google-auth-user.rule=Host(`auth.jaw.dev`) && PathPrefix(`/_oauth_user`)"
      - "traefik.http.routers.google-auth-user.entrypoints=websecure"
      - "traefik.http.routers.google-auth-user.priority=200"
      - "traefik.http.services.google-auth-user.loadbalancer.server.port=4181"

  google-auth-admin:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - TZ=America/Chicago
      - DEFAULT_PROVIDER=google
      - AUTH_HOST=auth.jaw.dev
      - URL_PATH=/_oauth_admin
      - COOKIE_DOMAIN=jaw.dev
      - COOKIE_NAME=_forward_auth_admin
      - CSRF_COOKIE_NAME=_forward_auth_admin_csrf
      - SECRET=${SECRET}
      - PROVIDERS_GOOGLE_CLIENT_ID=${PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${PROVIDERS_GOOGLE_CLIENT_SECRET}
      - WHITELIST=${WHITELIST_ADMINS:-no-one@example.invalid}
      - INSECURE_COOKIE=false
      - LOG_LEVEL=info
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.google-auth-admin.rule=Host(`auth.jaw.dev`) && PathPrefix(`/_oauth_admin`)"
      - "traefik.http.routers.google-auth-admin.entrypoints=websecure"
      - "traefik.http.routers.google-auth-admin.priority=200"
      - "traefik.http.services.google-auth-admin.loadbalancer.server.port=4181"

networks:
  traefik:
    external: true
