services:
  commit:
    image: ghcr.io/wajeht/commit:b09a783
    networks:
      - traefik
    env_file:
      - .enc.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commit.rule=Host(`commit.jaw.dev`)"
      - "traefik.http.routers.commit.entrypoints=websecure"
      - "traefik.http.services.commit.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
