services:
  miniflux:
    image: miniflux/miniflux:2.2.17@sha256:802ab7d045826d047883476e2310bf59f5d9b3875f7a8106fa0c43638d01fd64
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - BASE_URL=https://rss.jaw.dev
    depends_on:
      miniflux-db:
        condition: service_healthy
    networks:
      - proxy
      - miniflux-internal
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    labels:
      caddy: rss.jaw.dev
      caddy.import: auth
      caddy.reverse_proxy: "{{upstreams 8080}}"

  miniflux-db:
    image: postgres:18-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29
    env_file:
      - .env
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /home/jaw/data/miniflux/db:/var/lib/postgresql/data
    networks:
      - miniflux-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniflux"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

networks:
  proxy:
    external: true
  miniflux-internal:
