services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.2.17@sha256:802ab7d045826d047883476e2310bf59f5d9b3875f7a8106fa0c43638d01fd64
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - BASE_URL=https://rss.jaw.dev
    depends_on:
      miniflux-db:
        condition: service_healthy
    networks:
      - traefik
      - miniflux-internal
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miniflux.rule=Host(`rss.jaw.dev`)"
      - "traefik.http.routers.miniflux.entrypoints=websecure"
      - "traefik.http.routers.miniflux.middlewares=google-auth@file"
      - "traefik.http.services.miniflux.loadbalancer.server.port=8080"
  miniflux-db:
    container_name: miniflux-db
    image: postgres:18-alpine@sha256:88f300be8635fe8a9ed4c18a68ba497fb6df1215fd2b074895afd027bd3e1006
    env_file:
      - .env
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /home/jaw/data/miniflux/db:/var/lib/postgresql/data
    networks:
      - miniflux-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniflux"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

networks:
  traefik:
    external: true
  miniflux-internal:
