services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.17.5
    environment:
      - TZ=America/Chicago
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
      - /home/jaw/plex/audiobooks:/audiobooks
      - /home/jaw/plex/podcasts:/podcasts
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.wajeht.com`)"
        - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
        - "traefik.http.routers.audiobookshelf.tls.certresolver=cloudflare"
        - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"

volumes:
  audiobookshelf-config:
  audiobookshelf-metadata:

networks:
  traefik:
    external: true
