services:
  plausible:
    container_name: plausible
    image: ghcr.io/plausible/community-edition:v2.1.4@sha256:4c2553516d09e3c7b1b9c39cca04a04c28c871f525adc8dbb7a2a8a20fed0857
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    env_file:
      - .env
    environment:
      - BASE_URL=https://plausible.jaw.dev
      - DATABASE_URL=postgres://plausible:${POSTGRES_PASSWORD}@plausible-db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible-events-db:8123/plausible_events
      - DISABLE_REGISTRATION=invite_only
    depends_on:
      plausible-db:
        condition: service_healthy
      plausible-events-db:
        condition: service_healthy
    networks:
      - traefik
      - plausible-internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`plausible.jaw.dev`)"
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"
  plausible-db:
    container_name: plausible-db
    image: postgres:18-alpine@sha256:035b9ab53cfa147d7202b61f5f7782b939ae815b7d6bc81c96b7b42ff1fca950
    env_file:
      - .env
    environment:
      - POSTGRES_USER=plausible
      - POSTGRES_DB=plausible
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /home/jaw/data/plausible/db:/var/lib/postgresql/data
    networks:
      - plausible-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plausible"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M

  plausible-events-db:
    container_name: plausible-events-db
    image: clickhouse/clickhouse-server:26.1-alpine@sha256:5ba33b32cf22441530a7793a8b65b5cb9fff37c3779fe4cabb2a4b9cb460dd35
    volumes:
      - /home/jaw/data/plausible/events:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - plausible-internal
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  traefik:
    external: true
  plausible-internal:
