services:
  ddns-updater:
    container_name: ddns-updater
    image: ghcr.io/qdm12/ddns-updater:v2.9.0@sha256:ed73f1fb7ab54a8a8fa26001eecc77cc8be56cdf3fb0ca91fee831124bcbb696
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
      - PERIOD=5m
    volumes:
      - /home/jaw/data/ddns-updater:/updater/data
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ddns-updater.rule=Host(`ddns.jaw.dev`)"
      - "traefik.http.routers.ddns-updater.entrypoints=websecure"
      - "traefik.http.routers.ddns-updater.middlewares=google-auth@file"
      - "traefik.http.services.ddns-updater.loadbalancer.server.port=8000"
networks:
  traefik:
    external: true
