services:
  ddns-updater:
    container_name: ddns-updater
    image: ghcr.io/qdm12/ddns-updater:v2.9.0
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - HTTP_TIMEOUT=10s
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - BACKUP_PERIOD=24h
      - LOG_LEVEL=info
      - SHOUTRRR_ADDRESSES=ntfy://ntfy:80/ddns-updater
    volumes:
      - /home/jaw/data/ddns-updater:/updater/data
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "/updater/ddns-updater", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ddns-updater.rule=Host(`ddns.jaw.dev`)"
      - "traefik.http.routers.ddns-updater.entrypoints=websecure"
      - "traefik.http.routers.ddns-updater.middlewares=google-auth@file"
      - "traefik.http.services.ddns-updater.loadbalancer.server.port=8000"
networks:
  traefik:
    external: true
