services:
  ip:
    image: ghcr.io/wajeht/ip:3fee0ad
    environment:
      - TZ=America/Chicago
      - PORT=80
      - NODE_ENV=production
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    labels:
      caddy: ip.jaw.dev
      caddy.import: public
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  proxy:
    external: true
