services:
  git:
    image: ghcr.io/wajeht/git:924cd2d@sha256:211f9244c8883020094690e8f60e6f96835a72a1b8f3c51ef0cb87949e8ea604
    environment:
      - TZ=America/Chicago
      - APP_PORT=80
      - APP_ENV=production
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`git.jaw.dev`)"
      - "traefik.http.routers.git.entrypoints=websecure"
      - "traefik.http.services.git.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
