services:
  git:
    image: ghcr.io/wajeht/git:394d4cb
    environment:
      - TZ=America/Chicago
      - APP_PORT=80
      - APP_ENV=production
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    labels:
      caddy: git.jaw.dev
      caddy.import: public
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  proxy:
    external: true
